# Generated by Django 4.0.4 on 2022-06-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tc_user',
            table='TC_user',
        ),
    ]
