# Generated by Django 4.0.4 on 2022-06-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_tc_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TC_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SelfIntroduction', models.CharField(max_length=200, verbose_name='自己紹介')),
                ('hobby', models.CharField(max_length=100, verbose_name='趣味')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
