# Generated by Django 4.0.4 on 2022-06-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tc_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tc_profile',
            name='hobby',
        ),
        migrations.AlterField(
            model_name='tc_profile',
            name='SelfIntroduction',
            field=models.CharField(blank=True, max_length=200, verbose_name='自己紹介'),
        ),
    ]
